Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /author/
Not Found: /author/
Not Found: /favicon.ico
Internal Server Error: /search/
Traceback (most recent call last):
  File "/src/blog/views.py", line 80, in get_context_data
    assert(len(Post.objects.filter(title__icontains=search)) > 0)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 82, in get_context_data
    raise Http404
NameError: name 'Http404' is not defined
Not Found: /search/
Not Found: /search/
Not Found: /search/
Not Found: /search/
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 74, in get_context_data
    search = self.request.GET['search']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'search'
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 74, in get_context_data
    search = self.request.GET['search']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'search'
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 74, in get_context_data
    search = self.request.GET['search']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'search'
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 74, in get_context_data
    search = self.request.GET['search']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'search'
Not Found: /search
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 74, in get_context_data
    search = self.request.GET['search']
  File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'search'
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 76, in get_context_data
    if search == '':
NameError: name 'search' is not defined
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 76, in get_context_data
    context = listing(self.requets, Post.objects.filter(title_icontains=search))
AttributeError: 'SearchPageView' object has no attribute 'requets'
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 76, in get_context_data
    context = listing(self.request, Post.objects.filter(title_icontains=search))
AttributeError: 'SearchPageView' object has no attribute 'requets'
Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 149, in get
    context = self.get_context_data(**kwargs)
  File "/src/blog/views.py", line 76, in get_context_data
    context = listing(self.request, Post.objects.filter(title_icontains=search))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 841, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 859, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1164, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1028, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'title_icontains' into field. Choices are: author, author_id, content, content_id, id, image, pub_date, status, status_id, tags, title
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /favicon.ico
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /author/cat/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /tag/python/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /tag/python/
Not Found: /tag/docker/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /tag/docker/
Not Found: /tag/javascript/
Not Found: /tag/test/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /tag/docker/
Not Found: /tag/javascript/
Not Found: /tag/test/
Not Found: /author/Jack/
Not Found: /author/David/
Not Found: /author/test/
Not Found: /post/0/
Not Found: /post/1/
Not Found: /post/2/
Not Found: /post/3/
Not Found: /post/4/
Not Found: /post/5/
Not Found: /post/6/
Not Found: /post/7/
Not Found: /post/8/
Not Found: /post/9/
Not Found: /tag/docker/
Not Found: /tag/javascript/
Not Found: /tag/test/
Not Found: /favicon.ico
Not Found: /post/undefined/
Not Found: /post/undefined/
Not Found: /post/undefined/
Not Found: /post/undefined/
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
